- name :  set prompt
  ansible.builtin.shell: set-prompt {{app_name}}-{{env}}

- name: load nodejs
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs

- name : Copy MongoDB repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
  
- name: Install MongoDB Client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed

- name: Load Master Data
  ansible.builtin.shell: mongodb-{{ env }}.adevsecopsb08.online </app/db/master-data.js

- name: restart catalogue Service
  ansible.builtin.systemd_service:
     name: catalogue
     state: restarted

    