- name: Add Application User 
  ansible.builtin.user:
      name: roboshop 

- name: Delete old Application directory
  ansible.builtin.file:
        path: /app  
        state: absent

- name : Create Application directory
  ansible.builtin.file:
      path: /app
      state: directory
  
- name: Download and extarct application content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}-v3.zip
    dest: /app
    remote_src: yes